### ISSUE TITLE
Support for socket-io v3 and v4 

### ISSUE THREAD

**Issue by mrwhoknows55** [icerockdev/moko-socket-io#31]
Currently moko-socket-io uses [v1.0.0](https://github.com/icerockdev/moko-socket-io/blob/32ed1bcbfb92565702d1f053ed17ff216ff124df/gradle/libs.versions.toml#L4) of socket.io-client-java which is only [compatible upto v2 socket-io server](https://github.com/socketio/socket.io-client-java?tab=readme-ov-file#compatibility). 
Should update it to v2.x.x which adds support to v3 and v4

**Comment by bwoodlt** [comment]
Any update on this? We're looking to use this library but its still very much on v1.0.0 of socketIo

**Comment by mrwhoknows55** [comment]
I'd worked on it but as the sample backend uses v1 it's not working with breaking changes of client, so I have to find/write new sample server with socket-io v3. I'll try to raise a PR this weekend

**Comment by Alex009** [comment]
will be available in 0.6.0
